### ISSUE TITLE
Boltdb breaks drive with (panic: invalid page type:) or (panic: above high water mark)

### ISSUE THREAD

**Issue by pghmcfc** [agrez/drive-google#2]
A sufficiently large number of (upstream) users have found an issue with drive's use of boltdb that there's a wiki page on how to recover from the issue:

https://github.com/odeke-em/drive/wiki/Boltdb-breaks-drive-with-(panic:-invalid-page-type:)-or-(panic:--above-high-water-mark)

Could you please update to the current release (0.3.9.1), which seems to fix the issue for me at least.

**Comment by agrez** [comment]
Done! Refer commit:  https://github.com/agrez/drive-google/commit/8a4a01404c3f903d4f33597678de218c3181b9a5

Thanks for opening the issue. Hope the newer f25 build helps your issue. FYI, f24 builds are no longer supported as a minimum Go version >= 1.7.x is now required.

Cheers!
Vaughan

**Comment by pghmcfc** [comment]
Thanks for the quick update. Fedora 25 is fine for me, and hopefully I'll see later in the week when I do my next backup push to google that the issue is resolved (I did today's using a fresh build from upstream).

Incidentally, if I do `drive-google version`, then on my build from upstream I get:
```
drive version: 0.3.9.1
Commit Hash: '9995dab8b2b59755100a7a4f993dc64aef5aa108'         
Go Version: go1.7.5
OS: linux/amd64
BuildTime: 2017-04-04 10:24:00.434072608 +0100 BST          
```
but on the copr version I get:
```
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT> 
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:
```
I guess this is down to the different build process used?

**Comment by agrez** [comment]
Yes, I've noticed this issue but never looked into it (mainly due to lack of time and its not a critical bug). If you find a fix, then let me know.
